name: e_commerce_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cloud_firestore: ^5.0.2
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  firebase_storage: ^12.1.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.7
  flutter_rating_bar: ^4.0.1
  get: ^4.6.6
  get_storage: ^2.1.1
  google_sign_in: ^6.2.1
  http: ^1.0.0
  iconsax: ^0.0.8
  image_picker: ^1.1.2
  intl: ^0.19.0
  logger: ^2.2.0
  lottie: ^3.1.2
  readmore: ^3.0.0
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.2.4
  velocity_x: ^4.1.2

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#272727"
  image: assets\logos\logo.png

  android: true
  ios: true
  web: false

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/
    - assets/icons/brands/
    - assets/icons/
    - assets/images/onBoardingImages/
    - assets/icons/categories/
    - assets/images/banners/
    - assets/payment_methods/

  fonts:
    - family: sans_regular
      fonts:
        - asset: assets/fonts/sans_regular.ttf

    - family: sans_semibold
      fonts:
        - asset: assets/fonts/sans_semibold.ttf

    - family: sans_bold
      fonts:
        - asset: assets/fonts/sans_bold.ttf
    # fonts:
    #   - family: Poppins
    #     fonts:
    #       - asset: assets/fonts/Poppins-Light.ttf
    #       - weight: 300
    #       - asset: assets/fonts/Poppins-Regular.ttf
    #       - weight: 400
    #       - asset: assets/fonts/Poppins-Italic.ttf
    #       - style: italic
    #       - asset: assets/fonts/Poppins-Medium.ttf
    #       - weight: 500
    #       - style: italic
    #       - asset: assets/fonts/CoolveticaRg-Regular 400.ttf
    #       - weight: 600
    # - asset: assets/fonts/Poppins-Bold.ttf
    # - weight: 700
    # - style: italic
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
