// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD91eUoc8kwnY0waDM7viVjGfrP8oJLYC8',
    appId: '1:444917115785:web:32f2ef8040dfa39d710f58',
    messagingSenderId: '444917115785',
    projectId: 'e-commerceapp-386e0',
    authDomain: 'e-commerceapp-386e0.firebaseapp.com',
    storageBucket: 'e-commerceapp-386e0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZFSL8oZcbMWqR0LxY-vBjBNO1ESAGBsI',
    appId: '1:444917115785:android:3ac1502a47fa585c710f58',
    messagingSenderId: '444917115785',
    projectId: 'e-commerceapp-386e0',
    storageBucket: 'e-commerceapp-386e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfqdFvLbwt7GU9bEvOhJr44Lj3dfbkl10',
    appId: '1:444917115785:ios:672b19e4869232dd710f58',
    messagingSenderId: '444917115785',
    projectId: 'e-commerceapp-386e0',
    storageBucket: 'e-commerceapp-386e0.appspot.com',
    androidClientId: '444917115785-9o8iq70mcm6m45kg6hvc0og5776clsrl.apps.googleusercontent.com',
    iosClientId: '444917115785-o2v830u59ejusosa4jr6vdb0mvidn2b0.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfqdFvLbwt7GU9bEvOhJr44Lj3dfbkl10',
    appId: '1:444917115785:ios:672b19e4869232dd710f58',
    messagingSenderId: '444917115785',
    projectId: 'e-commerceapp-386e0',
    storageBucket: 'e-commerceapp-386e0.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD91eUoc8kwnY0waDM7viVjGfrP8oJLYC8',
    appId: '1:444917115785:web:d6b87bdeac3449aa710f58',
    messagingSenderId: '444917115785',
    projectId: 'e-commerceapp-386e0',
    authDomain: 'e-commerceapp-386e0.firebaseapp.com',
    storageBucket: 'e-commerceapp-386e0.appspot.com',
  );
}